import './global.css';

export const metadata = {
  title: 'sWelcome to status-check!',
  description: 'Generated by create-nx-workspace',
};
console.log('werrf)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
